[build]
builder = "nixpacks"
buildCommand = "yarn install && NODE_ENV=production yarn build"

[deploy]
startCommand = "echo \"DATABASE_URL=$DATABASE_URL\" > .env && NODE_ENV=production yarn start"
healthcheck = "/health"
