[build]
builder = "nixpacks"
buildCommand = """
echo "DATABASE_URL=${DATABASE_URL}" > .env
echo "REDIS_URL=${REDIS_URL}" >> .env
echo "STORE_CORS=*" >> .env
echo "ADMIN_CORS=*" >> .env
echo "JWT_SECRET=supersecret" >> .env
echo "COOKIE_SECRET=supersecret" >> .env
yarn install --immutable && yarn medusa db:create && yarn medusa db:migrate && yarn run seed && yarn medusa user -e admin@test.com -p supersecret -i admin && yarn build
"""

[deploy]
startCommand = "yarn start"
healthcheck = "/health"
restartPolicyType = "on_failure"