[build]
builder = "nixpacks"
buildCommand = "yarn install --immutable && yarn build"

[deploy]
startCommand = "echo \"DATABASE_URL=$DATABASE_URL\" > .env && yarn medusa db:migrate && yarn start"
healthcheck = "/health"
