[build]
builder = "nixpacks"
buildCommand = "echo \"DATABASE_URL=$DATABASE_URL\nREDIS_URL=$REDIS_URL\nSTORE_CORS=*\nADMIN_CORS=*\nJWT_SECRET=supersecret\nCOOKIE_SECRET=supersecret\" > .env && yarn install --immutable && yarn medusa db:create && yarn medusa db:migrate && yarn run seed && yarn medusa user -e admin@test.com -p supersecret -i admin && yarn build"

[deploy]
startCommand = "yarn start"
healthcheck = "/health"
